#!/bin/bash
# Auto-generated by ctd_minimum_cover.py
# Deletes CTD files whose coverage is fully provided by other files.
# The remaining files preserve complete time coverage.

rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151107T011757.231076-20160203T075108.287602.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151112T235959.387746-20160301T180000.653717.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160203T075109.288025-20160516T000000.559495.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160324T050506.085710-20160711T000000.025662.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T055959.112187-20190311T180000.560954.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201122T235959.198893-20210315T000000.016139.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210314T235959.016346-20210705T000000.595883.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230101T000000.149650-20230120T115959.534201.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231228T055959.503935-20240417T120000.203436.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240125T041622.072379-20240506T000000.030980.nc"