#!/bin/bash
# Auto-generated by ctd_overlap_audit.py
# Deletes fully redundant CTD files (time range entirely covered by another file)

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171231T235959.416378-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180101T000000.415237-20180121T235959.179653.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171231T235959.416378-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180122T000000.179035-20180213T115959.077959.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171231T235959.416378-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180213T120000.077967-20180309T235959.801120.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171231T235959.416378-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180310T000000.801647-20180321T001400.555731.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181223T120000.871412.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20180802T235959.998085.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181223T120000.871412.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180804T000000.633817-20180915T235959.300739.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181223T120000.871412.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180916T000000.300331-20181013T235959.658478.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181223T120000.871412.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181015T000000.920887-20181108T115959.526737.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181223T120000.871412.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181108T120000.526849-20181201T235959.606006.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181223T115959.871819-20190506T180000.102783.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181226T000000.816635-20190116T235959.006813.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181223T115959.871819-20190506T180000.102783.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190117T000000.006824-20190212T115959.799442.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181223T115959.871819-20190506T180000.102783.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190212T120000.798200-20190309T115959.098296.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181223T115959.871819-20190506T180000.102783.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190309T120000.097162-20190331T235959.812827.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181223T115959.871819-20190506T180000.102783.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190401T000000.812002-20190423T235959.149910.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190506T175959.102774-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190519T000000.541449-20190611T235959.330860.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190506T175959.102774-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190612T000000.331705-20190614T051242.692351.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190708T115959.337234.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190708T120000.337137-20190802T115959.773776.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190802T120000.773784-20190825T235959.681274.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190826T000000.680969-20190918T115959.270637.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190918T120000.269707-20190927T184152.175125.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200805T115959.832593-20201224T180000.692901.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200831T000000.783833-20200920T115959.011035.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200805T115959.832593-20201224T180000.692901.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200920T120000.010514-20201012T235959.775598.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200805T115959.832593-20201224T180000.692901.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201013T000000.775496-20201109T115959.405553.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200805T115959.832593-20201224T180000.692901.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201110T000000.121150-20201201T115959.027001.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200805T115959.832593-20201224T180000.692901.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201202T000000.725595-20201221T235959.364359.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201224T175959.692481-20210518T180000.933655.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210117T120000.216898-20210211T115959.290539.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201224T175959.692481-20210518T180000.933655.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210211T120000.290541-20210305T235959.347947.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201224T175959.692481-20210518T180000.933655.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210306T000000.346906-20210331T115959.809939.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201224T175959.692481-20210518T180000.933655.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210331T120000.809212-20210424T115959.560973.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210518T175959.933028-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210522T120000.016487-20210616T115959.468612.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210518T175959.933028-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210616T120000.469656-20210711T115959.296014.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210518T175959.933028-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210711T120000.296223-20210802T115959.962259.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210518T175959.933028-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210802T120000.961324-20210804T190841.180708.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20220115T060000.420794.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210825T000000.608433-20210918T115959.346732.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20220115T060000.420794.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210918T120000.346011-20211010T235959.181675.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20220115T060000.420794.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211011T000000.182516-20211107T115959.411620.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20220115T060000.420794.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211107T120000.411522-20211129T235959.116959.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20220115T060000.420794.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211201T000000.790292-20211226T235959.250957.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20230203T000000.451900.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230108T120000.384295-20230130T235959.862951.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221231T235959.150689-20230224T084327.668331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230131T120000.573266-20230222T235959.601662.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221231T235959.150689-20230224T084327.668331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230203T055959.781400-20230224T084327.668331.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241227T175959.223351-20250509T180000.121459.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250117T120000.262878-20250211T235959.902956.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241227T175959.223351-20250509T180000.121459.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250212T000000.902234-20250305T235959.106715.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241227T175959.223351-20250509T180000.121459.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250306T000000.106825-20250327T235959.050680.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241227T175959.223351-20250509T180000.121459.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250328T000000.051417-20250419T115959.880961.nc"
