#!/bin/bash
# Auto-generated by ctd_overlap_audit.py
# Deletes fully redundant CTD files (time range entirely covered by another file)

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150510T120000.215421.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2014_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150424T172450.573911.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150518T000000.646750.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2014_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150510T120000.215421.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150424T172450.573911.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150101T000000.534516-20150119T115959.683761.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150424T172450.573911.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150119T120000.684073-20150209T115959.266726.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150424T172450.573911.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150209T120000.268081-20150227T235959.256657.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150424T172450.573911.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150228T000000.256242-20150320T115959.207610.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150424T172450.573911.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150320T120000.207299-20150408T115959.564114.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150510T120000.215421.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150408T120000.564010-20150426T235959.210864.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20141231T235959.533995-20150518T000000.646750.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150427T000000.211907-20150515T115959.468181.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150424T172451.574121-20150705T235959.089334.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150510T115959.215525-20150705T235959.089334.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150424T172451.574121-20150705T235959.089334.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150515T120000.468076-20150603T115959.511135.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150424T172451.574121-20150705T235959.089334.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150517T235959.647476-20150705T235959.089334.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150424T172451.574121-20150705T235959.089334.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150603T120000.511135-20150622T235959.527671.nc"

# Covered by: deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150424T172451.574121-20150705T235959.089334.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0001_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150623T000000.527360-20150705T235959.089334.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151107T011756.232005.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20150728T235959.904283.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151113T000000.386503.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151107T011756.232005.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151130T000000.854900.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151113T000000.386503.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151107T011756.232005.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150729T000000.904060-20150816T235959.211656.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151107T011756.232005.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150817T000000.210829-20150904T115959.848917.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151107T011756.232005.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150904T120000.848718-20150922T235959.229768.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151107T011756.232005.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150923T000000.229670-20151013T115959.836856.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151113T000000.386503.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151013T120000.837278-20151109T115959.817253.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20150708T220539.700577-20151130T000000.854900.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151109T120000.818511-20151127T235959.549603.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151107T011757.231076-20160203T075108.287602.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151128T000000.549298-20151216T115959.695096.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151107T011757.231076-20160203T075108.287602.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2015_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151216T120000.695000-20151231T235958.855969.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151107T011757.231076-20160203T075108.287602.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160101T000000.856298-20160119T115959.832305.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151112T235959.387746-20160301T180000.653717.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160119T120000.832207-20160206T235959.899924.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151112T235959.387746-20160301T180000.653717.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160207T000000.899410-20160225T115959.794980.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20151129T235959.854788-20160324T050505.085704.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160225T120000.796131-20160314T235959.505774.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160203T075109.288025-20160516T000000.559495.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160315T000000.504636-20160402T115959.199509.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160203T075109.288025-20160516T000000.559495.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160402T120000.199621-20160420T235959.634486.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160203T075109.288025-20160516T000000.559495.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160421T000000.634805-20160512T115959.112858.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160301T175959.653501-20160622T120000.737566.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160512T120000.112759-20160530T235959.906942.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160301T175959.653501-20160622T120000.737566.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160531T000000.906950-20160618T115959.281757.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160324T050506.085710-20160711T000000.025662.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160618T120000.281763-20160706T235959.194190.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160515T235959.558758-20160716T111049.607585.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160622T115959.737872-20160716T111049.607585.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160515T235959.558758-20160716T111049.607585.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160707T000000.194092-20160716T111049.607585.nc"

# Covered by: deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160515T235959.558758-20160716T111049.607585.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0002_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160710T235959.025447-20160716T111049.607585.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20161101T001820.136228.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20160805T235959.893022.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20161101T001820.136228.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20161101T001820.136228.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160806T000000.893439-20160824T235959.645849.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160818T175959.492332-20161206T120000.988138.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20161101T001820.136228.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160825T000000.646265-20160912T115959.974370.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20161101T001820.136228.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160912T120000.974060-20160930T235959.058791.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20161101T001820.136228.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161001T000000.059206-20161019T115959.769502.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161019T120000.769814-20161106T235959.799530.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161101T001821.136229-20170130T014303.019857.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161107T000000.798384-20161125T115959.047537.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161125T120000.047850-20161213T235959.354124.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161206T115959.989283-20170130T014303.019857.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2016_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20161214T000000.354853-20161231T235958.677209.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170101T000000.678980-20170120T115959.971173.nc"

# Covered by: deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20160718T174252.421331-20170130T014303.019857.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0003_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170120T120000.971799-20170130T014303.019857.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171123T000000.840398.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20170822T235959.926493.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171127T000000.530828.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171123T000000.840398.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171127T000000.530828.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171123T000000.840398.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170823T000000.925771-20170910T115959.461232.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171123T000000.840398.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170910T120000.461133-20170928T235959.352619.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171123T000000.840398.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170929T000000.352731-20171017T115959.700876.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171123T000000.840398.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171017T120000.700050-20171104T235959.071985.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20171127T000000.530828.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171105T000000.071574-20171124T115959.052820.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171122T235959.840079-20180317T000000.603714.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171124T120000.052516-20171215T115959.577744.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171215T120000.577750-20171231T235958.415953.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2017_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20171224T235959.897837-20180321T001400.555731.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180101T153820.335574-20180120T115959.203770.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180120T120000.203881-20180207T235959.840792.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180208T000000.840174-20180226T115959.391002.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180226T120000.390906-20180318T235959.986256.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180316T235959.604853-20180321T001400.555731.nc"

# Covered by: deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20170804T200441.032162-20180321T001400.555731.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0004_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180319T000000.985846-20180321T001400.555731.nc"

# Covered by: deployment0005_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180624T165600.731931-20180709T001301.994718.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0005_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180624T165600.731931-20180701T213819.372833.nc"

# Covered by: deployment0005_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180624T165600.731931-20180709T001301.994718.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0005_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180701T000000.867511-20180709T001301.994718.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181125T060000.112302.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20180728T235959.413343.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181126T000000.746949.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181125T060000.112302.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181130T064647.879244.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181126T000000.746949.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181217T000000.485697.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181130T064647.879244.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181125T060000.112302.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180729T000000.413354-20180820T235959.957187.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181125T060000.112302.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180821T000000.957092-20180925T115959.978965.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181125T060000.112302.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180925T120000.979288-20181018T084220.403580.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181125T060000.112302.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181019T201406.543980-20181106T235959.302943.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181126T000000.746949.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181107T000000.302848-20181125T115959.680612.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20180710T170527.140820-20181217T000000.485697.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T120000.679476-20181213T235959.345289.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T235959.746938-20190318T000000.207331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181130T064648.879251-20190318T000000.207331.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T055959.112187-20190311T180000.560954.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181214T000000.345612-20190101T000000.743189.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T055959.112187-20190311T180000.560954.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190101T000001.742366-20190118T235959.845587.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T055959.112187-20190311T180000.560954.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190119T000000.845285-20190206T115959.792782.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T055959.112187-20190311T180000.560954.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190206T120000.792895-20190224T235959.207768.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181125T235959.746938-20190318T000000.207331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190225T000000.207466-20190315T115959.271513.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190311T175959.560630-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190315T120000.271524-20190402T235959.171888.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190311T175959.560630-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190317T235959.207321-20190614T051242.692351.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190311T175959.560630-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190403T000000.172626-20190421T115959.199853.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190311T175959.560630-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190421T120000.199654-20190510T115959.483280.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190311T175959.560630-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190510T120000.483080-20190528T235959.960308.nc"

# Covered by: deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190311T175959.560630-20190614T051242.692351.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190529T000000.959486-20190614T051242.692351.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190703T115959.291554.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190703T120000.291667-20190721T235959.611571.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190722T000000.611265-20190813T115959.262221.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190813T120000.262230-20190831T235959.681995.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190901T000000.682314-20190919T235959.650771.nc"

# Covered by: deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190614T231354.539487-20190927T184152.175125.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0007_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190920T000000.651402-20190927T184152.175125.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201123T000000.198165.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20200824T235959.129850.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201128T000000.147228.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201123T000000.198165.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201130T225829.341226.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201128T000000.147228.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201123T000000.198165.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200825T000000.129850-20200913T235959.627555.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201123T000000.198165.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200914T000000.627765-20201002T115959.289144.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201123T000000.198165.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201002T120000.289146-20201020T235959.042914.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201123T000000.198165.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201021T000000.043437-20201110T115959.760754.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20200803T164413.888856-20201130T225829.341226.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201110T120000.760652-20201128T235959.413385.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201122T235959.198893-20210315T000000.016139.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201129T000000.412761-20201217T115959.605047.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201127T235959.147644-20210319T120000.431316.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201130T225830.341254-20210317T085641.859601.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201122T235959.198893-20210315T000000.016139.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201217T120000.605257-20201231T235958.575069.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201122T235959.198893-20210315T000000.016139.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210101T000000.575069-20210121T115959.194534.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201122T235959.198893-20210315T000000.016139.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210121T120000.194640-20210208T235959.616079.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201122T235959.198893-20210315T000000.016139.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210209T000000.614309-20210227T115959.267265.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201127T235959.147644-20210319T120000.431316.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210227T120000.266433-20210317T235959.053065.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210314T235959.016346-20210705T000000.595883.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210318T000000.053483-20210405T235959.755315.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210317T085642.860957-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210319T115959.431314-20210708T120000.554350.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210314T235959.016346-20210705T000000.595883.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210406T000000.755837-20210424T115959.560973.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210314T235959.016346-20210705T000000.595883.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210424T120000.560953-20210512T235959.993093.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210314T235959.016346-20210705T000000.595883.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210513T000000.993197-20210531T115959.607495.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210314T235959.016346-20210705T000000.595883.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210531T120000.607809-20210618T235959.365563.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210317T085642.860957-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210619T000000.365356-20210707T235959.697327.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210317T085642.860957-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210704T235959.595775-20210804T190841.180708.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210317T085642.860957-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210708T000000.697746-20210726T115959.888137.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210317T085642.860957-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210708T115959.554246-20210804T190841.180708.nc"

# Covered by: deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210317T085642.860957-20210804T190841.180708.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210726T120000.887617-20210804T190841.180708.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211217T180000.875580.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20210912T115959.861328.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211220T000000.592313.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211217T180000.875580.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211223T063248.370115.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211220T000000.592313.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211217T180000.875580.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210912T120000.860607-20210930T235959.882037.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211217T180000.875580.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211001T000000.882148-20211020T115959.994746.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211217T180000.875580.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211020T120000.998919-20211111T235959.976912.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211217T180000.875580.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211112T000000.976191-20211130T115959.395599.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210824T233256.569856-20211220T000000.592313.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211130T120000.394981-20211218T235959.025618.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211219T000000.025936-20211231T235959.097192.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220101T000000.097718-20220119T115959.716798.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220119T120000.716909-20220206T235959.759194.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220207T000000.760033-20220225T115959.979452.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220225T120000.979876-20220315T235959.635902.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211217T175959.876304-20220405T180000.708918.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220316T000000.636325-20220403T115959.494046.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220403T120000.493219-20220421T235959.270502.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220405T175959.709014-20220804T000000.219773.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220410T235959.662444-20220902T204459.535113.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220422T000000.270132-20220510T115959.059772.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220510T120000.059883-20220528T235959.929785.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220529T000000.929063-20220625T235959.097436.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220626T000000.097653-20220714T115959.143323.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220714T120000.143540-20220801T235959.413267.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220802T000000.413692-20220821T040048.018394.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220803T235959.219037-20220902T204459.535113.nc"

# Covered by: deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20211223T063249.370230-20220902T204459.535113.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220821T190212.982463-20220902T204459.535113.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221219T000000.517671.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221003T235959.727206.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20230105T060000.510542.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221219T000000.517671.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20230116T000000.532180.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20230105T060000.510542.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221219T000000.517671.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221004T000000.727103-20221022T115959.025937.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221219T000000.517671.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221022T120000.025940-20221109T235959.933973.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221219T000000.517671.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221110T000000.933976-20221128T115959.370887.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20221219T000000.517671.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221128T120000.370231-20221218T235959.518295.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220915T181349.594332-20230105T060000.510542.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20221219T000000.517671-20221231T235958.149543.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230105T055959.511165-20230224T084327.668331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230115T235959.531865-20230224T084327.668331.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230105T055959.511165-20230224T084327.668331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230120T120000.533266-20230207T235959.938775.nc"

# Covered by: deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230105T055959.511165-20230224T084327.668331.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0010_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230208T000000.938256-20230224T084327.668331.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20231228T060000.503527.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20230904T235959.488554.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20240212T000000.874083.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20231228T060000.503527.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20231228T060000.503527.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230905T000000.488142-20230923T115959.540370.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20231228T060000.503527.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230923T120000.541107-20231011T235959.978188.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20240212T000000.874083.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230924T235959.426340-20240125T041621.072892.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20231228T060000.503527.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231012T000000.978204-20231030T115959.273632.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20231228T060000.503527.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231030T120000.279895-20231117T235959.124972.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20240212T000000.874083.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231118T000000.124979-20231229T115959.892377.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20240212T000000.874083.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2023_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231229T120000.892281-20231231T235958.766323.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20240212T000000.874083.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240101T000000.766750-20240119T115959.449471.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20230817T212929.521060-20240212T000000.874083.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240119T120000.448957-20240206T235959.875334.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231228T055959.503935-20240417T120000.203436.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240207T000000.876070-20240225T115959.763240.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231228T055959.503935-20240417T120000.203436.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240225T120000.763664-20240314T235959.166228.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20231228T055959.503935-20240417T120000.203436.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240315T000000.166755-20240404T115959.308445.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240125T041622.072379-20240506T000000.030980.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240404T120000.308347-20240422T235959.358127.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240211T235959.873971-20240702T063319.865896.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240423T000000.358656-20240529T115959.314355.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240417T115959.202701-20240809T063045.498432.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240505T235959.031179-20240809T063045.498432.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240211T235959.873971-20240702T063319.865896.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240529T120000.314467-20240617T235959.640407.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240417T115959.202701-20240809T063045.498432.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240618T000000.640518-20240712T115959.059289.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240417T115959.202701-20240809T063045.498432.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240702T063320.866527-20240809T063045.498432.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240417T115959.202701-20240809T063045.498432.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240712T120000.059402-20240731T115959.153324.nc"

# Covered by: deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240417T115959.202701-20240809T063045.498432.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240731T120000.153538-20240809T063045.498432.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241122T072829.648539.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20240829T235959.714924.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241129T120000.376830.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241122T072829.648539.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241216T000000.135762.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241129T120000.376830.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241122T072829.648539.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240830T000000.714932-20240917T115959.681332.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241122T072829.648539.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240917T120000.682066-20241006T115959.146015.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241122T072829.648539.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241006T120000.146334-20241024T235959.173611.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241122T072829.648539.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241025T000000.173619-20241112T115959.593854.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240809T203132.739326-20241216T000000.135762.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241112T120000.594278-20241130T235959.808550.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241129T115959.376825-20250320T060000.631502.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241201T000000.809807-20241219T235959.849594.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241215T235959.135859-20250410T124327.799585.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241220T000000.849601-20241231T235958.309352.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250101T000000.308210-20250119T115959.698459.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250119T120000.697321-20250207T235959.214104.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250208T000000.214006-20250226T115959.591425.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250226T120000.590600-20250316T235959.138358.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250317T000000.138365-20250404T115959.192090.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250320T055959.631494-20250708T060000.139407.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250404T120000.192721-20250422T235959.289444.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250410T124328.799383-20250728T000000.489667.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250423T000000.289348-20250511T115959.658246.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250511T120000.657940-20250529T235959.487435.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250530T000000.486506-20250616T235959.009390.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250617T000000.009190-20250704T235959.763316.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250705T000000.764260-20250723T115959.525719.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250708T055959.139191-20250805T142747.771470.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250723T120000.525831-20250805T142747.771470.nc"

# Covered by: deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20241122T072830.648546-20250805T142747.771470.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250727T235959.489659-20250805T142747.771470.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251123T101005.525062.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20250901T235959.754151.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251202T000000.663734.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251123T101005.525062.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251215T000000.085007.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251202T000000.663734.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251123T101005.525062.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250902T000000.754367-20250919T235959.429973.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251123T101005.525062.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250920T000000.430085-20251007T235959.536412.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251123T101005.525062.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251008T000000.536524-20251025T235959.760831.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251123T101005.525062.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251026T000000.761880-20251113T115959.455867.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250814T232320.067702-20251202T000000.663734.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251113T120000.456293-20251201T235959.664461.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251123T101006.524654-20260101T000000.312004.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251201T235959.664461-20260101T000000.312004.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251123T101006.524654-20260101T000000.312004.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251202T000000.663734-20251220T115959.584506.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251123T101006.524654-20260101T000000.312004.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251214T235959.085311-20260101T000000.312004.nc"

# Covered by: deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251123T101006.524654-20260101T000000.312004.nc
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0014_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20251220T120000.585139-20251231T235958.311886.nc"
