#!/bin/bash
# Auto-generated by ctd_minimum_cover.py
# Deletes CTD files whose coverage is fully provided by other files.
# The remaining files preserve complete time coverage.

rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2018_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20181202T000000.605700-20181225T235959.816416.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2019_ctd/deployment0006_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20190424T000000.150232-20190518T235959.541439.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2020_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20201222T120000.157039-20210117T115959.216690.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2021_ctd/deployment0008_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20210424T120000.560953-20210522T115959.016382.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2022_ctd/deployment0009_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20220511T120000.673835-20220531T235959.937483.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2024_ctd/deployment0011_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20240117T055959.232818-20240626T000000.121740.nc"
rm "/home/rob/ooi/ooinet/rca/SlopeBase/scalar/2025_ctd/deployment0012_RS01SBPS-SF01A-2A-CTDPFA102-streamed-ctdpf_sbe43_sample_20250419T120000.881592-20250511T235959.973129.nc"