# Jupyter cell: CTD minimum cover analysis
# Finds the minimal set of files that preserves full time coverage,
# then generates a deletion script for all others.

import re
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from pathlib import Path
from datetime import datetime

print("CTD Minimum Cover Analysis")
print("=" * 60)

BASE = Path("~/ooi/ooinet/rca/SlopeBase/scalar").expanduser()
YEARS = range(2014, 2027)

def parse_time_range(filename):
    pattern = r'_(\d{8}T\d{6})\.\d+-(\d{8}T\d{6})\.\d+\.nc$'
    match = re.search(pattern, filename)
    if not match:
        return None, None
    fmt = "%Y%m%dT%H%M%S"
    try:
        return datetime.strptime(match.group(1), fmt), datetime.strptime(match.group(2), fmt)
    except ValueError:
        return None, None

# --- Collect all CTD files ---
all_files = []
for year in YEARS:
    folder = BASE / f"{year}_ctd"
    if not folder.exists():
        continue
    for f in sorted(folder.glob("*.nc")):
        start, end = parse_time_range(f.name)
        if start and end:
            all_files.append({'name': f.name, 'path': f, 'start': start, 'end': end})

all_files.sort(key=lambda x: x['start'])
print(f"Total CTD files: {len(all_files)}")

# --- Greedy interval cover algorithm ---
# At each step: among all files whose start <= current frontier,
# pick the one with the furthest end time. Advance frontier. Repeat.
# This is the classic greedy minimum interval cover and is optimal.

def minimum_cover(files):
    """
    Returns the minimal subset of files that covers the same
    total time span as all files combined, with no gaps.
    Files must be sorted by start time.
    """
    if not files:
        return [], []

    keep = []
    deletable = []

    # Work through the timeline left to right
    frontier = files[0]['start']   # earliest start
    end_of_all = max(f['end'] for f in files)

    remaining = list(files)

    while frontier < end_of_all:
        # Candidates: all files that start at or before the current frontier
        candidates = [f for f in remaining if f['start'] <= frontier]

        if not candidates:
            # Gap in coverage - advance frontier to next file start
            next_file = min(remaining, key=lambda x: x['start'])
            frontier = next_file['start']
            candidates = [next_file]

        # Pick the candidate with the furthest end time
        best = max(candidates, key=lambda x: x['end'])
        keep.append(best)
        remaining.remove(best)

        # Everything else that started before or at frontier and ends
        # before or at best.end is now redundant given best
        newly_redundant = [
            f for f in remaining
            if f['start'] <= frontier and f['end'] <= best['end']
        ]
        for f in newly_redundant:
            deletable.append(f)
            remaining.remove(f)

        frontier = best['end']

    # Any remaining files not yet classified
    for f in remaining:
        # Check if covered by the keep set
        covered = any(k['start'] <= f['start'] and k['end'] >= f['end'] for k in keep)
        if covered:
            deletable.append(f)
        else:
            keep.append(f)

    return keep, deletable

keep, deletable = minimum_cover(all_files)

print(f"Files needed for full coverage: {len(keep)}")
print(f"Files deletable without losing coverage: {len(deletable)}")

if deletable:
    total_size = sum(f['path'].stat().st_size for f in deletable) / (1024*1024)
    print(f"Recoverable space: {total_size:.1f} MB")

# --- Write deletion script ---
script_path = Path("~/argosy/delete_overlaps2.sh").expanduser()

if deletable:
    lines = [
        "#!/bin/bash",
        "# Auto-generated by ctd_minimum_cover.py",
        "# Deletes CTD files whose coverage is fully provided by other files.",
        "# The remaining files preserve complete time coverage.",
        "",
    ]
    for f in sorted(deletable, key=lambda x: x['start']):
        lines.append(f"rm \"{f['path']}\"")

    script_path.write_text("\n".join(lines))
    script_path.chmod(0o755)
    print(f"\nDeletion script written to: {script_path}")
    print(f"Review and run with:  bash {script_path}")
else:
    print("\nNo deletable files found - set is already minimal.")

# --- Plot ---
fig, ax = plt.subplots(figsize=(14, max(4, len(all_files) * 0.25)))

keep_names = {f['name'] for f in keep}

for i, f in enumerate(all_files):
    color = 'steelblue' if f['name'] in keep_names else 'orange'
    alpha = 0.7
    ax.barh(i,
            (f['end'] - f['start']).total_seconds() / 86400,
            left=mdates.date2num(f['start']),
            height=0.7, color=color, alpha=alpha, edgecolor='none')

ax.xaxis_date()
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
ax.xaxis.set_major_locator(mdates.YearLocator())
ax.set_xlabel('Date', fontsize=12)
ax.set_ylabel('File index (chronological)', fontsize=12)
ax.set_title(f'CTD Minimum Cover ({len(all_files)} files)\n'
             f'Blue=keep ({len(keep)})  Orange=deletable ({len(deletable)})', fontsize=13)
ax.set_xlim(mdates.date2num(datetime(2014, 1, 1)),
            mdates.date2num(datetime(2026, 12, 31)))
ax.grid(True, axis='x', alpha=0.3)
ax.set_yticks([])

from matplotlib.patches import Patch
ax.legend(handles=[
    Patch(facecolor='steelblue', alpha=0.7, label=f'Keep ({len(keep)})'),
    Patch(facecolor='orange',    alpha=0.7, label=f'Deletable ({len(deletable)})'),
], loc='upper left')

plt.tight_layout()
plot_path = Path("~/argosy/ctd_minimum_cover.png").expanduser()
plt.savefig(plot_path, dpi=150, bbox_inches='tight')
plt.show()
print(f"Plot saved to {plot_path}")
